apiVersion: 1

policies:
  - orgId: 1
    receiver: IronScout Slack
    group_by:
      - alertname
      - severity
    routes:
      - receiver: IronScout Slack
        matchers:
          - severity=critical
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 1h
      - receiver: IronScout Slack
        matchers:
          - severity=warning
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
